---
collections:
  - name: ansible.posix
  - name: community.crypto
  - name: community.general
  - name: robertdebock.bootstrap
  - name: robertdebock.buildtools
  - name: robertdebock.epel
  - name: robertdebock.postgres
  - name: robertdebock.python_pip
