---

name: Build and deploy Collection on Ansible Galaxy
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Upload collection to Ansible Galaxy
        uses: ansible/ansible-publish-action@v1.0.0
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
